export const orderFields = [
    {
        name: "customerName",
        label: "Customer Name",
        type: "text",
        required: true,
        placeholder: "Enter Customer Name",
    },
    {
        name: "orderItem",
        label: "Order Item",
        type: "text",
        required: true,
        placeholder: "Enter Item Name",
    },
    {
        name: "quantity",
        label: "Quantity",
        type: "number",
        required: true,
        min: "1",
        step: "1",
        placeholder: "Enter Quantity",
    },
    {
        name: "orderDateTime",
        label: "Order Date & Time",
        type: "datetime-local",
        required: true,
    },
    {
        name: "amount",
        label: "Amount",
        type: "number",
        required: true,
        placeholder: "0.00",
        step: "1",
        min: "0",
        prefix: "₹",
    },
    {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Pending", "Shipped", "Delivered", "Cancelled"],
    },
    {
        name: "paymentMethod",
        label: "Payment Method",
        type: "select",
        required: true,
        options: ["Cash on Delivery", "Credit Card", "UPI", "Net Banking"],
    },
    {
        name: "deliveredDateTime",
        label: "Delivered Date & Time",
        type: "datetime-local",
        required: false,
    },
    {
        name: "deliveredAddress",
        label: "Delivered Address",
        type: "textarea",
        required: true,
    },
];
export const transactionFields = [
    {
        name: "userName",
        label: "Payer / Recipient  Name",
        type: "text",
        required: true,
        placeholder: "Enter Payer / Recipient Name",
    },
    {
        name: "transactionDateTime",
        label: "Transaction Date & Time",
        type: "datetime-local",
        required: true,
    },
    {
        name: "amount",
        label: "Amount",
        type: "number",
        required: true,
        placeholder: "0.00",
        step: "1",
        min: "0",
        prefix: "₹",
    },
    {
        name: "type",
        label: "Type",
        type: "select",
        required: true,
        options: ["Credit", "Debit"],
    },
    {
        name: "method",
        label: "Payment Method",
        type: "select",
        required: true,
        options: ["Cash", "Credit Card", "UPI", "Net Banking"],
    },
    {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Successful", "Pending", "Failed"],
    },
    {
        name: "reference",
        label: "Reference",
        type: "text",
        required: false,
        placeholder: "Enter Reference (optional)",
    },
];